# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      context: "./initdb"
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: better_shop,better_shop_testing
      POSTGRES_PASSWORD: local_pass
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
