jwt:
  prod:
    secret: 'M0stS3cur3dP4$$' #TODO: Change with your own value
    ttl: '1h'
  dev:
    secret: 'secret'
    ttl: '30m'
  test:
    secret: 'secret'
    ttl: '1h'
db:
  prod:
    type: 'postgres'
    host: 'initdb.service' #TODO: Update with Production DB service name or hostname
    port: 5432
    name: 'postgres'
    user: 'postgres'
    pass: 'password'
  dev:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    name: 'better_shop'
    user: 'postgres'
    pass: 'local_pass'
  test:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    name: 'better_shop_testing'
    user: 'postgres'
    pass: 'local_pass'
